import type { EntityDefinition, GeneratedSourceFile } from "./types";
import { PROJECT_NAMESPACE } from "./types";

function fieldDefault(field: EntityDefinition["fields"][0]): string {
  if (field.isKey) return "";
  if (field.csharpType === "DateTime") return " = DateTime.UtcNow;";
  if (field.csharpType === "string") return ' = string.Empty;';
  return "";
}

export function generateEntityClasses(
  entities: EntityDefinition[]
): GeneratedSourceFile[] {
  return entities.map((entity) => {
    const props = entity.fields
      .map((f) => {
        const nullable = f.csharpType.endsWith("?") ? "" : f.isRequired ? "" : "?";
        const type = f.csharpType.replace("?", "");
        return `    public ${type}${nullable} ${f.name} { get; set; }${fieldDefault(f)}`;
      })
      .join("\n\n");

    const content = `using System;

namespace ${PROJECT_NAMESPACE}.Domain.Entities;

/// <summary>
/// Domain entity — generated by Franky (V23)
/// </summary>
public class ${entity.name}
{
${props}
}
`;

    return {
      id: `entity-${entity.name}`,
      path: `${PROJECT_NAMESPACE}.Domain/Entities`,
      fileName: `${entity.name}.cs`,
      category: "entity",
      agent: "Franky",
      language: "csharp",
      content,
    };
  });
}

export function generateDbContext(entities: EntityDefinition[]): GeneratedSourceFile {
  const dbSets = entities
    .map((e) => `    public DbSet<${e.name}> ${e.tableName} { get; set; } = null!;`)
    .join("\n");

  const config = entities
    .map(
      (e) => `        modelBuilder.Entity<${e.name}>(entity =>
        {
            entity.ToTable("${e.tableName}");
            entity.HasKey(x => x.Id);
        });`
    )
    .join("\n\n");

  const content = `using Microsoft.EntityFrameworkCore;
using ${PROJECT_NAMESPACE}.Domain.Entities;

namespace ${PROJECT_NAMESPACE}.Infrastructure.Data;

/// <summary>
/// EF Core DbContext — generated by Franky (V23)
/// </summary>
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

${dbSets}

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

${config}
    }
}
`;

  return {
    id: "infrastructure-dbcontext",
    path: `${PROJECT_NAMESPACE}.Infrastructure/Data`,
    fileName: "AppDbContext.cs",
    category: "infrastructure",
    agent: "Franky",
    language: "csharp",
    content,
  };
}

export function generateRepositories(
  entities: EntityDefinition[]
): GeneratedSourceFile[] {
  const files: GeneratedSourceFile[] = [];

  for (const entity of entities) {
    const iface = `using ${PROJECT_NAMESPACE}.Domain.Entities;

namespace ${PROJECT_NAMESPACE}.Infrastructure.Repositories;

public interface I${entity.name}Repository
{
    Task<IReadOnlyList<${entity.name}>> GetAllAsync(CancellationToken cancellationToken = default);
    Task<${entity.name}?> GetByIdAsync(int id, CancellationToken cancellationToken = default);
    Task<${entity.name}> AddAsync(${entity.name} entity, CancellationToken cancellationToken = default);
    Task UpdateAsync(${entity.name} entity, CancellationToken cancellationToken = default);
    Task DeleteAsync(int id, CancellationToken cancellationToken = default);
}
`;

    const impl = `using Microsoft.EntityFrameworkCore;
using ${PROJECT_NAMESPACE}.Domain.Entities;
using ${PROJECT_NAMESPACE}.Infrastructure.Data;

namespace ${PROJECT_NAMESPACE}.Infrastructure.Repositories;

public class ${entity.name}Repository : I${entity.name}Repository
{
    private readonly AppDbContext _context;

    public ${entity.name}Repository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<IReadOnlyList<${entity.name}>> GetAllAsync(CancellationToken cancellationToken = default)
    {
        return await _context.${entity.tableName}.AsNoTracking().ToListAsync(cancellationToken);
    }

    public async Task<${entity.name}?> GetByIdAsync(int id, CancellationToken cancellationToken = default)
    {
        return await _context.${entity.tableName}.FindAsync(new object[] { id }, cancellationToken);
    }

    public async Task<${entity.name}> AddAsync(${entity.name} entity, CancellationToken cancellationToken = default)
    {
        entity.CreatedAt = DateTime.UtcNow;
        _context.${entity.tableName}.Add(entity);
        await _context.SaveChangesAsync(cancellationToken);
        return entity;
    }

    public async Task UpdateAsync(${entity.name} entity, CancellationToken cancellationToken = default)
    {
        entity.UpdatedAt = DateTime.UtcNow;
        _context.${entity.tableName}.Update(entity);
        await _context.SaveChangesAsync(cancellationToken);
    }

    public async Task DeleteAsync(int id, CancellationToken cancellationToken = default)
    {
        var entity = await GetByIdAsync(id, cancellationToken);
        if (entity is null) return;
        _context.${entity.tableName}.Remove(entity);
        await _context.SaveChangesAsync(cancellationToken);
    }
}
`;

    files.push({
      id: `repo-iface-${entity.name}`,
      path: `${PROJECT_NAMESPACE}.Infrastructure/Repositories`,
      fileName: `I${entity.name}Repository.cs`,
      category: "infrastructure",
      agent: "Franky",
      language: "csharp",
      content: iface,
    });

    files.push({
      id: `repo-impl-${entity.name}`,
      path: `${PROJECT_NAMESPACE}.Infrastructure/Repositories`,
      fileName: `${entity.name}Repository.cs`,
      category: "infrastructure",
      agent: "Franky",
      language: "csharp",
      content: impl,
    });
  }

  return files;
}
