import type { EntityDefinition, GeneratedSourceFile } from "./types";
import { PROJECT_NAMESPACE } from "./types";

export function generateSqlScript(entities: EntityDefinition[]): GeneratedSourceFile {
  const tables = entities
    .map((entity) => {
      const cols = entity.fields
        .map((f) => `    ${f.name} ${f.sqlType}`)
        .join(",\n");
      return `-- Table: ${entity.tableName}\nCREATE TABLE [dbo].[${entity.tableName}] (\n${cols}\n);\nGO`;
    })
    .join("\n\n");

  const content = `-- Database schema — generated by Zoro (V23)
-- Entity Framework Core compatible SQL Server script

${tables}
`;

  return {
    id: "migration-sql",
    path: "Database/Scripts",
    fileName: "InitialSchema.sql",
    category: "migration",
    agent: "Zoro",
    language: "sql",
    content,
  };
}

export function generateDatabaseDesignDoc(
  entities: EntityDefinition[],
  zoroNotes: string
): GeneratedSourceFile {
  const tables = entities
    .map(
      (e) =>
        `### ${e.name} (\`${e.tableName}\`)\n\n| Column | Type |\n|--------|------|\n${e.fields.map((f) => `| ${f.name} | ${f.sqlType} |`).join("\n")}`
    )
    .join("\n\n");

  const content = `# Database Design

> Generated by Zoro · V23 Real Database Generator

${tables}

## Backend Notes

${zoroNotes.slice(0, 4000)}
`;

  return {
    id: "zoro-db-design",
    path: "docs",
    fileName: "DatabaseDesign.md",
    category: "docs",
    agent: "Zoro",
    language: "markdown",
    content,
  };
}

export function generateEfMigration(entities: EntityDefinition[]): GeneratedSourceFile {
  const upOps = entities
    .map((entity) => {
      const cols = entity.fields
        .map((f) => {
          const nullable = f.isRequired ? ".IsRequired()" : "";
          return `                .Property(e => e.${f.name})${nullable}`;
        })
        .join("\n");

      return `            migrationBuilder.CreateTable(
                name: "${entity.tableName}",
                columns: table => new
                {
${entity.fields.map((f) => `                    ${f.name} = table.Column<${mapCsharpToMigrationType(f.csharpType)}>(nullable: ${!f.isRequired})`).join(",\n")}
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_${entity.tableName}", x => x.Id);
                });`;
    })
    .join("\n\n");

  const downOps = entities
    .map((e) => `            migrationBuilder.DropTable(name: "${e.tableName}");`)
    .join("\n");

  const content = `using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ${PROJECT_NAMESPACE}.Infrastructure.Migrations;

/// <summary>
/// EF Core migration — generated by Zoro (V23)
/// </summary>
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
${upOps}
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
${downOps}
    }
}
`;

  return {
    id: "migration-ef",
    path: `${PROJECT_NAMESPACE}.Infrastructure/Migrations`,
    fileName: "20260101000000_InitialCreate.cs",
    category: "migration",
    agent: "Zoro",
    language: "csharp",
    content,
  };
}

function mapCsharpToMigrationType(csharpType: string): string {
  const t = csharpType.replace("?", "");
  const map: Record<string, string> = {
    int: "int",
    long: "long",
    bool: "bool",
    decimal: "decimal",
    double: "double",
    DateTime: "DateTime",
    Guid: "Guid",
    string: "string",
  };
  return map[t] ?? "string";
}
