import type { EntityDefinition, GeneratedSourceFile } from "./types";
import { PROJECT_NAMESPACE } from "./types";

export function generateUnitTests(
  entities: EntityDefinition[]
): GeneratedSourceFile[] {
  const files: GeneratedSourceFile[] = [];

  for (const entity of entities) {
    const content = `using Microsoft.AspNetCore.Mvc;
using Moq;
using Xunit;
using ${PROJECT_NAMESPACE}.API.Controllers;
using ${PROJECT_NAMESPACE}.Application.DTOs;
using ${PROJECT_NAMESPACE}.Domain.Entities;
using ${PROJECT_NAMESPACE}.Infrastructure.Repositories;

namespace ${PROJECT_NAMESPACE}.Tests;

/// <summary>
/// xUnit CRUD tests — generated by Usopp (V23)
/// </summary>
public class ${entity.name}ControllerTests
{
    private readonly Mock<I${entity.name}Repository> _repository = new();

    [Fact]
    public async Task GetAll_ReturnsOkWithItems()
    {
        _repository.Setup(r => r.GetAllAsync(default))
            .ReturnsAsync(new List<${entity.name}> { new() { Id = 1, Name = "Sample" } });

        var controller = new ${entity.name}Controller(_repository.Object);
        var result = await controller.GetAll(default);

        var ok = Assert.IsType<OkObjectResult>(result.Result);
        Assert.NotNull(ok.Value);
    }

    [Fact]
    public async Task GetById_WhenMissing_ReturnsNotFound()
    {
        _repository.Setup(r => r.GetByIdAsync(999, default))
            .ReturnsAsync((${entity.name}?)null);

        var controller = new ${entity.name}Controller(_repository.Object);
        var result = await controller.GetById(999, default);

        Assert.IsType<NotFoundResult>(result.Result);
    }

    [Fact]
    public async Task Create_ReturnsCreatedAtAction()
    {
        _repository.Setup(r => r.AddAsync(It.IsAny<${entity.name}>(), default))
            .ReturnsAsync(((${entity.name} e, CancellationToken _) => { e.Id = 1; return e; }));

        var controller = new ${entity.name}Controller(_repository.Object);
        var request = new ${entity.name}CreateRequest { Name = "New ${entity.name}" };
        var result = await controller.Create(request, default);

        Assert.IsType<CreatedAtActionResult>(result.Result);
    }

    [Fact]
    public async Task Update_WhenMissing_ReturnsNotFound()
    {
        _repository.Setup(r => r.GetByIdAsync(1, default))
            .ReturnsAsync((${entity.name}?)null);

        var controller = new ${entity.name}Controller(_repository.Object);
        var result = await controller.Update(1, new ${entity.name}UpdateRequest { Name = "Updated" }, default);

        Assert.IsType<NotFoundResult>(result);
    }

    [Fact]
    public async Task Delete_WhenMissing_ReturnsNotFound()
    {
        _repository.Setup(r => r.GetByIdAsync(1, default))
            .ReturnsAsync((${entity.name}?)null);

        var controller = new ${entity.name}Controller(_repository.Object);
        var result = await controller.Delete(1, default);

        Assert.IsType<NotFoundResult>(result);
    }
}
`;

    files.push({
      id: `test-${entity.name}`,
      path: `${PROJECT_NAMESPACE}.Tests`,
      fileName: `${entity.name}ControllerTests.cs`,
      category: "test",
      agent: "Usopp",
      language: "csharp",
      content,
    });
  }

  files.push({
    id: "test-project",
    path: `${PROJECT_NAMESPACE}.Tests`,
    fileName: `${PROJECT_NAMESPACE}.Tests.csproj`,
    category: "test",
    agent: "Usopp",
    language: "csharp",
    content: `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\${PROJECT_NAMESPACE}.API\\${PROJECT_NAMESPACE}.API.csproj" />
    <ProjectReference Include="..\\${PROJECT_NAMESPACE}.Infrastructure\\${PROJECT_NAMESPACE}.Infrastructure.csproj" />
  </ItemGroup>

</Project>
`,
  });

  return files;
}

export function generateTestPlanDoc(usoppNotes: string): GeneratedSourceFile {
  return {
    id: "usopp-test-plan",
    path: "docs",
    fileName: "TestPlan.md",
    category: "docs",
    agent: "Usopp",
    language: "markdown",
    content: `# QA & xUnit Test Plan

> Generated by Usopp · V23

${usoppNotes.slice(0, 5000)}
`,
  };
}
