import type { ProjectArtifact } from "@/app/types/artifacts";
import type { EntityDefinition, GeneratedSourceFile } from "@/lib/project-generator/types";
import { PROJECT_NAMESPACE } from "@/lib/project-generator/types";
import type { DatabaseDesignContract, ForeignKeyDefinition } from "@/lib/database-designer/entity-relationship";
import type { MigrationProgressStep } from "./database-status";

const MIGRATION_ID = "20260119120000_InitialCreate";

function mapEfType(csharpType: string): string {
  const t = csharpType.replace("?", "");
  const map: Record<string, string> = {
    int: "int",
    long: "long",
    bool: "bool",
    decimal: "decimal",
    double: "double",
    DateTime: "DateTime",
    Guid: "Guid",
    string: "string",
  };
  return map[t] ?? "string";
}

function propertyConfig(field: EntityDefinition["fields"][0]): string {
  if (field.name === "Name" && field.csharpType.includes("string")) {
    return 'builder.Property(x => x.Name).IsRequired().HasMaxLength(200);';
  }
  if (field.isRequired && field.csharpType.includes("string") && field.name !== "Name") {
    return `builder.Property(x => x.${field.name}).IsRequired();`;
  }
  if (field.name === "CreatedAt") {
    return 'builder.Property(x => x.CreatedAt).HasDefaultValueSql("GETUTCDATE()");';
  }
  return "";
}

export function generateEntityConfigurations(
  entities: EntityDefinition[],
  databaseDesign?: DatabaseDesignContract | null
): GeneratedSourceFile[] {
  return entities.map((entity) => {
    const fieldLines = entity.fields
      .map((f) => {
        const cfg = propertyConfig(f);
        return cfg ? `        ${cfg}` : "";
      })
      .filter(Boolean)
      .join("\n");

    const relationshipLines =
      databaseDesign?.fluentConfigurations
        .filter((c) => c.entity === entity.name)
        .map((c) => `        ${c.code.split("\n").join("\n        ")}`)
        .join("\n\n") ?? "";

    const relationshipBlock = relationshipLines
      ? `\n\n${relationshipLines}`
      : "";

    const content = `using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ${PROJECT_NAMESPACE}.Domain.Entities;

namespace ${PROJECT_NAMESPACE}.Infrastructure.Data.Configurations;

/// <summary>
/// EF Core entity configuration — generated by Franky (V31)
/// </summary>
public class ${entity.name}Configuration : IEntityTypeConfiguration<${entity.name}>
{
    public void Configure(EntityTypeBuilder<${entity.name}> builder)
    {
        builder.ToTable("${entity.tableName}");
        builder.HasKey(x => x.Id);
${fieldLines}${relationshipBlock}
    }
}
`;

    return {
      id: `config-${entity.name}`,
      path: `${PROJECT_NAMESPACE}.Infrastructure/Data/Configurations`,
      fileName: `${entity.name}Configuration.cs`,
      category: "infrastructure",
      agent: "Franky",
      language: "csharp",
      content,
    };
  });
}

export function generateAppDbContextV24(entities: EntityDefinition[]): GeneratedSourceFile {
  const dbSets = entities
    .map((e) => `    public DbSet<${e.name}> ${e.tableName} { get; set; } = null!;`)
    .join("\n");

  const content = `using Microsoft.EntityFrameworkCore;
using ${PROJECT_NAMESPACE}.Domain.Entities;

namespace ${PROJECT_NAMESPACE}.Infrastructure.Data;

/// <summary>
/// EF Core DbContext — generated by Franky (V24)
/// Ready for: dotnet ef migrations add InitialCreate
/// </summary>
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

${dbSets}

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
    }
}
`;

  return {
    id: "infrastructure-dbcontext",
    path: `${PROJECT_NAMESPACE}.Infrastructure/Data`,
    fileName: "AppDbContext.cs",
    category: "infrastructure",
    agent: "Franky",
    language: "csharp",
    content,
  };
}

export function generateMigrationFiles(
  entities: EntityDefinition[],
  databaseDesign?: DatabaseDesignContract | null
): GeneratedSourceFile[] {
  const fkByEntity = new Map<string, ForeignKeyDefinition[]>();
  if (databaseDesign) {
    for (const fk of databaseDesign.foreignKeys) {
      const list = fkByEntity.get(fk.entity) ?? [];
      list.push(fk);
      fkByEntity.set(fk.entity, list);
    }
  }

  const upOps = entities
    .map((entity) => {
      const fks = fkByEntity.get(entity.name) ?? [];
      const fkConstraints = fks
        .map(
          (fk) =>
            `                    table.ForeignKey(
                        name: "FK_${entity.tableName}_${fk.referencesEntity}",
                        column: x => x.${fk.property},
                        principalTable: "${entities.find((e) => e.name === fk.referencesEntity)?.tableName ?? fk.referencesEntity + "s"}",
                        principalColumn: "${fk.referencesProperty}");`
        )
        .join("\n");

      return `            migrationBuilder.CreateTable(
                name: "${entity.tableName}",
                columns: table => new
                {
${entity.fields.map((f) => `                    ${f.name} = table.Column<${mapEfType(f.csharpType)}>(nullable: ${!f.isRequired})`).join(",\n")}
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_${entity.tableName}", x => x.Id);
${fkConstraints}
                });`;
    })
    .join("\n\n");

  const downOps = entities
    .map((e) => `            migrationBuilder.DropTable(name: "${e.tableName}");`)
    .join("\n");

  const migrationCs = `using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ${PROJECT_NAMESPACE}.Infrastructure.Migrations;

/// <summary>
/// EF Core migration — generated by Franky (V24)
/// </summary>
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
${upOps}
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
${downOps}
    }
}
`;

  const designerCs = `using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ${PROJECT_NAMESPACE}.Infrastructure.Data;

#nullable disable

namespace ${PROJECT_NAMESPACE}.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("${MIGRATION_ID}")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
${entities.map((e) => `        modelBuilder.Entity("${PROJECT_NAMESPACE}.Domain.Entities.${e.name}", b => { b.ToTable("${e.tableName}"); });`).join("\n")}
#pragma warning restore 612, 618
    }
}
`;

  const snapshotCs = `using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ${PROJECT_NAMESPACE}.Infrastructure.Data;

#nullable disable

namespace ${PROJECT_NAMESPACE}.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
${entities.map((e) => `        modelBuilder.Entity("${PROJECT_NAMESPACE}.Domain.Entities.${e.name}", b => { b.ToTable("${e.tableName}"); });`).join("\n")}
#pragma warning restore 612, 618
    }
}
`;

  return [
    {
      id: "migration-initial",
      path: `${PROJECT_NAMESPACE}.Infrastructure/Migrations`,
      fileName: `${MIGRATION_ID}.cs`,
      category: "migration",
      agent: "Franky",
      language: "csharp",
      content: migrationCs,
    },
    {
      id: "migration-designer",
      path: `${PROJECT_NAMESPACE}.Infrastructure/Migrations`,
      fileName: `${MIGRATION_ID}.Designer.cs`,
      category: "migration",
      agent: "Franky",
      language: "csharp",
      content: designerCs,
    },
    {
      id: "migration-snapshot",
      path: `${PROJECT_NAMESPACE}.Infrastructure/Migrations`,
      fileName: "AppDbContextModelSnapshot.cs",
      category: "migration",
      agent: "Franky",
      language: "csharp",
      content: snapshotCs,
    },
  ];
}

export function generateMigrationPreview(
  entities: EntityDefinition[],
  migrationFiles: GeneratedSourceFile[]
): string {
  const tables = entities
    .map(
      (e) =>
        `  • ${e.tableName} (${e.fields.length} columns) — PK: Id`
    )
    .join("\n");

  const files = migrationFiles.map((f) => `  • ${f.fileName}`).join("\n");

  return `# EF Core Migration Preview

> Generated by Franky · V24 Migration Runner

## Migration: InitialCreate

**Migration ID:** ${MIGRATION_ID}

### Tables to create

${tables}

### Generated migration files

${files}

### Up() summary

${entities.map((e) => `- CREATE TABLE [${e.tableName}]`).join("\n")}

### Visual Studio 2022 workflow

1. Open \`${PROJECT_NAMESPACE}.sln\`
2. Set **Package Manager Default Project** → \`${PROJECT_NAMESPACE}.Infrastructure\`
3. Run in Package Manager Console:

\`\`\`powershell
Add-Migration InitialCreate -Project ${PROJECT_NAMESPACE}.Infrastructure -StartupProject ${PROJECT_NAMESPACE}.API
Update-Database -Project ${PROJECT_NAMESPACE}.Infrastructure -StartupProject ${PROJECT_NAMESPACE}.API
\`\`\`

Or use CLI:

\`\`\`bash
dotnet ef migrations add InitialCreate --project ${PROJECT_NAMESPACE}.Infrastructure --startup-project ${PROJECT_NAMESPACE}.API
dotnet ef database update --project ${PROJECT_NAMESPACE}.Infrastructure --startup-project ${PROJECT_NAMESPACE}.API
\`\`\`

> Pre-generated migration files are included — you may run \`database update\` directly after restore.
`;
}

export function migrationFilesToArtifacts(
  files: GeneratedSourceFile[],
  preview: string
): ProjectArtifact[] {
  const createdAt = new Date().toISOString();
  const artifacts: ProjectArtifact[] = files.map((f) => ({
    id: f.id,
    name: f.fileName,
    type: f.fileName.endsWith(".sql") ? "sql" : "csharp",
    content: f.content,
    agent: f.agent,
    createdAt,
  }));

  artifacts.push({
    id: "migration-preview",
    name: "MigrationPreview.md",
    type: "markdown",
    content: preview,
    agent: "Franky",
    createdAt,
  });

  return artifacts;
}

export function getMigrationProgressSteps(): MigrationProgressStep[] {
  return [
    { id: "ctx", label: "AppDbContext Generated", done: false, agent: "Franky" },
    { id: "config", label: "Entity Configurations Generated", done: false, agent: "Franky" },
    { id: "migration", label: "InitialCreate Migration Generated", done: false, agent: "Franky" },
    { id: "designer", label: "Migration Designer Generated", done: false, agent: "Franky" },
    { id: "snapshot", label: "Model Snapshot Generated", done: false, agent: "Franky" },
    { id: "preview", label: "Migration Preview Ready", done: false, agent: "Franky" },
  ];
}

export { MIGRATION_ID };
