export const PROJECT_SOLUTION_FILE = `
    Microsoft Visual Studio Solution File
    `;

export const DEFAULT_PROGRAM_CS = `
var builder =
    WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

var app = builder.Build();

app.MapControllers();

app.Run();
`;

export const API_CSPROJ = `
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
`;

export const APPLICATION_CSPROJ = `
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
`;

export const DOMAIN_CSPROJ = `
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
`;

export const INFRASTRUCTURE_CSPROJ = `
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
`;

export const APPSETTINGS_JSON = `
{
  "ConnectionStrings": {
    "DefaultConnection":
      "Server=.;Database=MyProjectDb;Trusted_Connection=True;"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  }
}
`;

export const README_MD = `
# AI Generated Solution

Generated By:
AI Development Crew V6

Architecture:

- MyProject.API
- MyProject.Application
- MyProject.Domain
- MyProject.Infrastructure

Tech Stack:

- ASP.NET Core
- Entity Framework Core
- SQL Server
- JWT Authentication
`;
