import type { ProjectArtifact } from "@/app/types/artifacts";

export type AgentOutputs = {
  requirement: string;
  robin: string;
  zoro: string;
  nami: string;
  franky: string;
  usopp: string;
};

type ArtifactSpec = {
  id: string;
  name: string;
  type: "markdown" | "sql" | "text";
  agent: string;
  build: (outputs: AgentOutputs) => string;
};

function extractSection(text: string, headings: string[]): string | null {
  for (const heading of headings) {
    const re = new RegExp(
      `(?:^|\\n)#+\\s*${escapeRe(heading)}[^\\n]*\\n([\\s\\S]*?)(?=\\n#+\\s|$)`,
      "i"
    );
    const match = text.match(re);
    if (match?.[1]?.trim()) return match[1].trim();
  }
  return null;
}

function escapeRe(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function extractSqlBlocks(text: string): string {
  const blocks: string[] = [];
  const fenced = text.matchAll(/```(?:sql)?\s*([\s\S]*?)```/gi);
  for (const match of fenced) {
    const block = match[1].trim();
    if (/create\s+table|alter\s+table|insert\s+into/i.test(block)) {
      blocks.push(block);
    }
  }
  if (blocks.length > 0) return blocks.join("\n\n");

  const lines = text.split("\n");
  const sqlLines: string[] = [];
  let inSql = false;
  for (const line of lines) {
    if (/^(create|alter|insert|drop)\s+/i.test(line.trim())) inSql = true;
    if (inSql) {
      sqlLines.push(line);
      if (line.trim().endsWith(";")) inSql = false;
    }
  }
  return sqlLines.join("\n").trim();
}

function wrapDocument(title: string, agent: string, body: string, fallback: string) {
  const content = body.trim() || fallback.trim();
  return `# ${title}

> Generated by **${agent}** · AI Dev Dashboard V22

${content}
`;
}

const ARTIFACT_SPECS: ArtifactSpec[] = [
  {
    id: "robin-requirement",
    name: "Requirement.md",
    type: "markdown",
    agent: "Robin",
    build: ({ requirement, robin }) =>
      wrapDocument(
        "Business Requirements",
        "Robin",
        extractSection(robin, [
          "Business Requirements",
          "Requirements",
          "Requirement Analysis",
          "Overview",
        ]) ??
          `## Original Brief\n\n${requirement}\n\n## Analysis\n\n${robin}`,
        robin
      ),
  },
  {
    id: "robin-user-stories",
    name: "UserStories.md",
    type: "markdown",
    agent: "Robin",
    build: ({ robin }) =>
      wrapDocument(
        "User Stories",
        "Robin",
        extractSection(robin, [
          "User Stories",
          "User Story",
          "Stories",
          "Features",
        ]) ?? robin,
        robin
      ),
  },
  {
    id: "zoro-api-spec",
    name: "API-Spec.md",
    type: "markdown",
    agent: "Zoro",
    build: ({ zoro }) =>
      wrapDocument(
        "API Specification",
        "Zoro",
        extractSection(zoro, ["API", "Endpoints", "REST API", "API Design"]) ??
          zoro,
        zoro
      ),
  },
  {
    id: "zoro-database",
    name: "Database.sql",
    type: "sql",
    agent: "Zoro",
    build: ({ zoro }) => {
      const sql =
        extractSqlBlocks(zoro) ||
        extractSection(zoro, ["Database", "Schema", "Data Model", "Tables"]) ||
        `-- Database schema derived from backend plan\n-- Agent: Zoro\n\n${zoro}`;
      return sql.startsWith("--") ? sql : `-- Generated by Zoro · V22\n\n${sql}`;
    },
  },
  {
    id: "nami-ui-spec",
    name: "UI-Spec.md",
    type: "markdown",
    agent: "Nami",
    build: ({ nami }) =>
      wrapDocument(
        "UI Specification",
        "Nami",
        extractSection(nami, [
          "UI Specification",
          "UI Design",
          "Screens",
          "Frontend Plan",
        ]) ?? nami,
        nami
      ),
  },
  {
    id: "nami-screen-flow",
    name: "ScreenFlow.md",
    type: "markdown",
    agent: "Nami",
    build: ({ nami }) =>
      wrapDocument(
        "Screen Flow",
        "Nami",
        extractSection(nami, [
          "Screen Flow",
          "Navigation",
          "User Flow",
          "Wireflow",
        ]) ?? nami,
        nami
      ),
  },
  {
    id: "franky-architecture",
    name: "Architecture.md",
    type: "markdown",
    agent: "Franky",
    build: ({ franky }) =>
      wrapDocument(
        "System Architecture",
        "Franky",
        extractSection(franky, [
          "Architecture",
          "System Architecture",
          "Architecture Review",
        ]) ?? franky,
        franky
      ),
  },
  {
    id: "franky-technical-design",
    name: "TechnicalDesign.md",
    type: "markdown",
    agent: "Franky",
    build: ({ franky }) =>
      wrapDocument(
        "Technical Design",
        "Franky",
        extractSection(franky, [
          "Technical Design",
          "Design Patterns",
          "Scalability",
          "Improvements",
        ]) ?? franky,
        franky
      ),
  },
  {
    id: "usopp-test-cases",
    name: "TestCases.md",
    type: "markdown",
    agent: "Usopp",
    build: ({ usopp }) =>
      wrapDocument(
        "Test Cases",
        "Usopp",
        extractSection(usopp, [
          "Test Cases",
          "Positive Test Cases",
          "QA Strategy",
        ]) ?? usopp,
        usopp
      ),
  },
  {
    id: "usopp-test-checklist",
    name: "TestChecklist.md",
    type: "markdown",
    agent: "Usopp",
    build: ({ usopp }) =>
      wrapDocument(
        "Test Checklist",
        "Usopp",
        extractSection(usopp, [
          "Validation Checklist",
          "Checklist",
          "Sign-off Criteria",
          "Edge Cases",
        ]) ?? usopp,
        usopp
      ),
  },
];

export function generateProjectArtifacts(outputs: AgentOutputs): ProjectArtifact[] {
  const createdAt = new Date().toISOString();

  return ARTIFACT_SPECS.map((spec) => ({
    id: spec.id,
    name: spec.name,
    type: spec.type,
    agent: spec.agent,
    content: spec.build(outputs),
    createdAt,
  }));
}

export function getArtifactProgressSteps(
  artifacts: ProjectArtifact[]
): { id: string; label: string; done: boolean }[] {
  const labels: Record<string, string> = {
    "robin-requirement": "Requirements Complete",
    "robin-user-stories": "User Stories Complete",
    "zoro-api-spec": "API Specification Complete",
    "zoro-database": "Database Script Complete",
    "nami-ui-spec": "UI Specification Complete",
    "nami-screen-flow": "Screen Flow Complete",
    "franky-architecture": "Architecture Complete",
    "franky-technical-design": "Technical Design Complete",
    "usopp-test-cases": "Test Cases Complete",
    "usopp-test-checklist": "Test Checklist Complete",
  };

  const doneIds = new Set(artifacts.map((a) => a.id));
  return ARTIFACT_SPECS.map((spec) => ({
    id: spec.id,
    label: labels[spec.id] ?? spec.name,
    done: doneIds.has(spec.id),
  }));
}

export { ARTIFACT_SPECS };
